//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deputados
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.camara.gov.br/SitCamaraWS/Deputados", ConfigurationName="Deputados.DeputadosSoap")]
    public interface DeputadosSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.camara.gov.br/SitCamaraWS/Deputados/ObterPartidosCD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ObterPartidosCDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.camara.gov.br/SitCamaraWS/Deputados/ObterPartidosBlocoCD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ObterPartidosBlocoCDAsync(string idBloco, string numLegislatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.camara.gov.br/SitCamaraWS/Deputados/ObterLideresBancadas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ObterLideresBancadasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.camara.gov.br/SitCamaraWS/Deputados/ObterIdCadastroOrcamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ObterIdCadastroOrcamentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.camara.gov.br/SitCamaraWS/Deputados/ObterDetalhesDeputado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ObterDetalhesDeputadoAsync(string ideCadastro, string numLegislatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.camara.gov.br/SitCamaraWS/Deputados/ObterDeputados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ObterDeputadosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface DeputadosSoapChannel : Deputados.DeputadosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DeputadosSoapClient : System.ServiceModel.ClientBase<Deputados.DeputadosSoap>, Deputados.DeputadosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DeputadosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DeputadosSoapClient.GetBindingForEndpoint(endpointConfiguration), DeputadosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DeputadosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DeputadosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DeputadosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DeputadosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DeputadosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ObterPartidosCDAsync()
        {
            return base.Channel.ObterPartidosCDAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ObterPartidosBlocoCDAsync(string idBloco, string numLegislatura)
        {
            return base.Channel.ObterPartidosBlocoCDAsync(idBloco, numLegislatura);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ObterLideresBancadasAsync()
        {
            return base.Channel.ObterLideresBancadasAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ObterIdCadastroOrcamentoAsync()
        {
            return base.Channel.ObterIdCadastroOrcamentoAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ObterDetalhesDeputadoAsync(string ideCadastro, string numLegislatura)
        {
            return base.Channel.ObterDetalhesDeputadoAsync(ideCadastro, numLegislatura);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ObterDeputadosAsync()
        {
            return base.Channel.ObterDeputadosAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DeputadosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DeputadosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DeputadosSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.camara.leg.br/SitCamaraWS/Deputados.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DeputadosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.camara.leg.br/SitCamaraWS/Deputados.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DeputadosSoap,
            
            DeputadosSoap12,
        }
    }
}
